# databases:
#   - name: mysite
#     databaseName: mysite
#     user: mysite

services:
  - type: web
    name: amanrawat-portfolio
    runtime: python
    region: singapore
    plan: free
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: WEB_CONCURRENCY
        value: 4
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: mysite
      #     property: connectionString
      # - key: SECRET_KEY
      #   generateValue: true