# databases:
#   - name: mysite
#     databaseName: mysite
#     user: mysite

services:
  - type: web
    name: portfolio
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: WEB_CONCURRENCY
        value: 4
      - key: NODE_VERSION
        value: 20.10.0
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: mysite
      #     property: connectionString
      # - key: SECRET_KEY
      #   generateValue: true