# Generated by Django 4.2.8 on 2024-01-15 10:49

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('category_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category_name')),
            ],
            options={
                'verbose_name': 'Logo Category',
                'verbose_name_plural': 'Logo Categories',
            },
        ),
    ]
