# Generated by Django 4.2.8 on 2024-01-15 12:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logomaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo_category',
            name='id',
        ),
        migrations.AlterField(
            model_name='logo_category',
            name='category_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='category_name', primary_key=True, serialize=False),
        ),
    ]
