# Generated by Django 4.2.8 on 2024-01-15 12:53

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logomaker', '0002_remove_logo_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo_category',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logo_category',
            name='category_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='category_name'),
        ),
    ]
