# Generated by Django 4.2.8 on 2024-01-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Tuner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('excited', 'Excited'), ('calm', 'Calm'), ('stressed', 'Stressed'), ('relaxed', 'Relaxed'), ('energetic', 'Energetic'), ('anxious', 'Anxious'), ('melancholic', 'Melancholic')], max_length=50, verbose_name='Mood of AI')),
                ('language_style', models.CharField(choices=[('formal', 'Formal'), ('informal', 'Informal'), ('technical', 'Technical'), ('literary', 'Literary'), ('Persuasive', 'Persuasive'), ('academic', 'Academic'), ('humorous', 'Humorous'), ('satiristic', 'Satiristic')], max_length=50, verbose_name='Language Style')),
            ],
            options={
                'verbose_name': 'AI_Tuner',
                'verbose_name_plural': 'AI_Tuners',
            },
        ),
    ]
